### PR TITLE
Use tweaked leaflet code for touch detection.

### PR DESCRIPTION
**Pull request by matthewberryman**

### CODE REVIEW

**Comment by benatwork99** [comment]
I can't see the diff properly, because the file is minified it's just showing two large changed lines.

I did run this branch earlier when testing IE on a mobile and did not encounter any new errors but it was not an exhaustive test.

**Comment by benatwork99** [comment]
Also can I suggest we make a README file or similar containing a description of how we modified leaflet? So that if we want to update leaflet in the future we know how we need to patch it.

**Comment by matthewberryman** [comment]
You need to diff the Leaflet source code to see the change:
https://github.com/smart-facility/Leaflet/compare/v0.7.7...smart-facility:ie_touch_detection
I will document that in README.md for our fork of Leaflet.

**Comment by matthewberryman** [comment]
I thought it best to describe it in CHANGELOG.md rather than README.md: https://github.com/smart-facility/Leaflet/commit/d9cd22259d822bb15324f2e8f5749d4cb0ce908b

**Comment by benatwork99** [comment]
Thanks!

Later on when we review our vendor dependencies and use unminified versions of them we should include a note (or update the comment in leaflet.js) of the fork it comes from.

**Comment by benatwork99** [comment]
This change is now captured in https://github.com/smart-facility/petajakarta-web/pull/119, that PR is using a different file (unminified) so will close this PR

**Pull request closed without merging**
